_options is undefined at our transport
VeliovGroup/Mail-Time pull request #1
Opened 2017-10-25 08:41 UTC by sandro-k

We have the following error thrown when using the default configuration shown in the doc. With the proposed changes Mail-Time is able to send emails via node-mailer. 

```
[mail-time] Exception during runtime: TypeError: Cannot read property 'mailOptions' of undefined
    at mail-time/index.js:237:33
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[mail-time] Re-send Attempt #8, transport #0 to:  ***** TypeError: Cannot read property 'mailOptions' of undefined
    at mail-time/index.js:237:33
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

2017-10-25 19:08 UTC, dr-dimitru commented
Hello @sandro-k ,

Thank you for this PR. I need to run tests, can not reproduce using `nodemailer@2.7.2` what `nodemailer` version you're on?

2017-10-26 20:19 UTC, dr-dimitru requested changes

2017-10-26 20:19 UTC, dr-dimitru commented on index.js
> +          if (transport.options.mailOptions) {
We have done some __quick__ research looks like newer versions of NodeMailer has no `transport._options`, while older have it. I'm suggest to keep support for older versions.

```js
          if (transport._options && typeof transport._options === 'object' && transport._options.mailOptions) {
            _mailOpts = merge(_mailOpts, transport._options.mailOptions);
          }

          if (transport.options && typeof transport.options === 'object' && transport.options.mailOptions) {
            _mailOpts = merge(_mailOpts, transport.options.mailOptions);
          }
```

Will you update and push one more commit?

2017-10-26 20:20 UTC, dr-dimitru commented
@sandro-k wish to hear from you soon

2017-10-26 20:21 UTC, sandro-k commented on index.js
> +          if (transport.options.mailOptions) {
LGTM. I will update my PR.

2017-10-30 16:32 UTC, sandro-k commented
Generally I don't like to have the same logic twice in the code and would like to reduce it to one function call, but it would definitely make the code more difficult to reason about.

2017-10-31 09:08 UTC, dr-dimitru commented
@sandro-k agree to DRY policy. But it's only two variations of the single option, using `for` loop through array with only two elements... not today :)

2017-10-31 09:08 UTC, dr-dimitru approved these changes
👍

2017-10-31 09:09 UTC, merged